name: SQL query test with Github Actions using devcontainers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        runCmd: |
          make install
          make lint
          make test
