name: SQL query test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Runs make install
    - name: Run make install
      run: make install
      
    # Runs make test
    - name: Run make test
      run: make test
